feat: improve solution conformity check reliability

diff --git a/.github/workflows/trigger-day-scheduling.yml b/.github/workflows/trigger-day-scheduling.yml
--- a/.github/workflows/trigger-day-scheduling.yml
+++ b/.github/workflows/trigger-day-scheduling.yml
@@ -53,34 +53,8 @@ jobs:
         with:
           profile: minimal
           channel: ${{ matrix.repository.toolchain }}
-          bins: cargo-modules
-
-      - name: Input Repo check
-        if: ${{ !inputs.owner }}
-        env:
-          NO_COLOR: 1 # Needed to avoid issues with grep
-          GH_TOKEN: ${{ github.token }}
-        id: input_repo_check
-        run: |
-          gh repo clone ${{ matrix.repository.owner }}/${{ matrix.repository.name }} /tmp/solution_repo -- --depth=1
-          cd /tmp/solution_repo
-          if [ -n "${{ matrix.repository.crate }}" ]; then
-            STRUCTURE=$(cargo modules structure --lib --max-depth=1 -p ${{ matrix.repository.crate }})
-          else
-            STRUCTURE=$(cargo modules structure --lib --max-depth=1)
-          fi
-          echo "Crate structure:"
-          echo "$STRUCTURE"
-          # Check if the crate has the day1 module
-          if ! echo "$STRUCTURE" | grep -q 'mod day${{ inputs.day }}:'; then
-            echo "::warning::The day ${{ inputs.day }} module is missing. Skipping the run."
-            echo "valid=false" >> $GITHUB_OUTPUT
-          else
-            echo "valid=true" >> $GITHUB_OUTPUT
-          fi
 
       - name: Prepare the runner
-        if: ${{ steps.input_repo_check.outputs.valid == 'true' || inputs.owner }}
         working-directory: ./rust-runner
         run: |
           REPO_URL="https://github.com/${{ matrix.repository.owner }}/${{ matrix.repository.name }}"
@@ -92,8 +66,22 @@ jobs:
           echo "[toolchain]" > ../rust-toolchain.toml
           echo "channel = \"${{ matrix.repository.toolchain }}\"" >> ../rust-toolchain.toml
 
+      - name: Check solution conformity
+        id: input_repo_check
+        working-directory: ./rust-runner
+        env:
+          DAY_NUMBER: ${{ inputs.day }}
+        run: |
+          if ! cargo build --test test_build ; then
+            echo "::warning::The day ${{ inputs.day }} module is missing or malformed. Skipping the run."
+            echo "valid=false" >> $GITHUB_OUTPUT
+          else
+            echo "Solution is valid"
+            echo "valid=true" >> $GITHUB_OUTPUT
+          fi
+
       - name: Prepare the branch & schedule the run
-        if: ${{ (!inputs.skip_scheduling && steps.input_repo_check.outputs.valid == 'true') || inputs.owner }}
+        if: ${{ !inputs.skip_scheduling && steps.input_repo_check.outputs.valid == 'true' }}
         run: |
           git config --global user.name "codspeed-advent[bot]"
           git config --global user.email "codspeed-advent-bot@@users.noreply.github.com"
